# Use an official Python runtime as a base image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the pyproject.toml and poetry.lock files to the working directory
COPY pyproject.toml poetry.lock ./

# Install Poetry
RUN pip install poetry

# Configure Poetry to create virtual environments in the project directory
RUN poetry config virtualenvs.in-project true

# Install dependencies without dev packages for production
RUN poetry install

# Copy the source code
COPY ./src ./src

# Ensure the Poetry-created virtualenv is in PATH
ENV PATH="/app/.venv/bin:$PATH"

# Set PYTHONPATH so Uvicorn can find the src module
ENV PYTHONPATH="/app/src"
